### ISSUE TITLE
Member gets wrong validation result

### ISSUE THREAD

**Issue by rioda-org** [idena-network/idena-tg-bot#15]
Member gets wrong validation result message by bot, that he has passed validation but in fact this identity
0x54930c624858b43dc27859b7c78fcfafeea3eaef
had late submission, web app, sent flip decription keys 35 sec after short session started.

![image](https://user-images.githubusercontent.com/37978870/174458220-5fb27e12-2f0c-43d0-8e2a-e0b10025f901.png)

**Comment by ridenaio** [comment]
Hi! Please, run `/me` command in order to see the address, which is connected here. There were several cases, when different addresses were connected to telegram.

**Comment by rioda-org** [comment]
Hi, he got
My address: 0x54930c624858b43dc27859b7c78fcfafeea3eaef

**Comment by xpugur** [comment]
![bbbbbbbb](https://user-images.githubusercontent.com/18118067/178141621-2f9d07f3-b6b5-4632-b04f-8d8b17918c5e.JPG)
same for me, idena bot failed but not me  :))  i do not have any other account so there is no possiblity to connect wrong address :) 

  My address: 0xe312632fc34b235170627202665be27af47117d1
